export const MATCHLIST = {
  matches: [
    {
      id: 3986447,
      status: 'New',
      published: 'Yes',
      last_updated: '10/05/2019',
      league_name: 'Mid Essex Cricket League',
      league_id: '16868',
      competition_name: 'Division 3',
      competition_id: '85353',
      competition_type: 'League',
      match_type: 'Limited Overs',
      game_type: 'Standard',
      season: '2019',
      match_date: '04/05/2019',
      match_time: '13:00',
      ground_name: 'Brooklands, Mill Lane, Broomfield',
      ground_id: '',
      ground_latitude: '',
      ground_longitude: '',
      home_club_name: 'Broomfield CC',
      home_team_name: '1st XI',
      home_team_id: '50813',
      home_club_id: '1486',
      away_club_name: 'Navestock CC',
      away_team_name: '1st XI',
      away_team_id: '204935',
      away_club_id: '4513',
      umpire_1_name: '',
      umpire_1_id: '',
      umpire_2_name: '',
      umpire_2_id: '',
      umpire_3_name: '',
      umpire_3_id: '',
      referee_name: '',
      referee_id: '',
      scorer_1_name: '',
      scorer_1_id: '',
      scorer_2_name: '',
      scorer_2_id: '',
    },
    {
      id: 3925364,
      status: 'New',
      published: 'Yes',
      last_updated: '13/05/2019',
      league_name: '',
      league_id: '',
      competition_name: '',
      competition_id: '',
      competition_type: 'Friendly',
      match_type: 'Limited Overs',
      game_type: 'Standard',
      season: '2019',
      match_date: '05/05/2019',
      match_time: '14:00',
      ground_name: 'Mountnessing C.C., Coronation Playing Field',
      ground_id: '',
      ground_latitude: '',
      ground_longitude: '',
      home_club_name: 'Willow Herbs (Mountnessing) CC',
      home_team_name: 'Friendly XI',
      home_team_id: '49628',
      home_club_id: '6944',
      away_club_name: 'Navestock CC',
      away_team_name: 'Sunday XI',
      away_team_id: '50485',
      away_club_id: '4513',
      umpire_1_name: '',
      umpire_1_id: '',
      umpire_2_name: '',
      umpire_2_id: '',
      umpire_3_name: '',
      umpire_3_id: '',
      referee_name: '',
      referee_id: '',
      scorer_1_name: '',
      scorer_1_id: '',
      scorer_2_name: '',
      scorer_2_id: '',
    },
    {
      id: 3986448,
      status: 'New',
      published: 'Yes',
      last_updated: '13/05/2019',
      league_name: 'Mid Essex Cricket League',
      league_id: '16868',
      competition_name: 'Division 3',
      competition_id: '85353',
      competition_type: 'League',
      match_type: 'Limited Overs',
      game_type: 'Standard',
      season: '2019',
      match_date: '11/05/2019',
      match_time: '13:00',
      ground_name: 'Navestock C.C. Ground',
      ground_id: '6775',
      ground_latitude: '51.6542835',
      ground_longitude: '0.257747',
      home_club_name: 'Navestock CC',
      home_team_name: '1st XI',
      home_team_id: '204935',
      home_club_id: '4513',
      away_club_name: 'Rayleigh Fairview CC',
      away_team_name: '1st XI',
      away_team_id: '47294',
      away_club_id: '8094',
      umpire_1_name: '',
      umpire_1_id: '',
      umpire_2_name: '',
      umpire_2_id: '',
      umpire_3_name: '',
      umpire_3_id: '',
      referee_name: '',
      referee_id: '',
      scorer_1_name: '',
      scorer_1_id: '',
      scorer_2_name: '',
      scorer_2_id: '',
    },
    {
      id: 3949933,
      status: 'New',
      published: 'Yes',
      last_updated: '12/05/2019',
      league_name: 'Mid Essex Cricket League',
      league_id: '16868',
      competition_name: 'Division 8',
      competition_id: '85120',
      competition_type: 'League',
      match_type: 'Limited Overs',
      game_type: 'Standard',
      season: '2019',
      match_date: '11/05/2019',
      match_time: '13:00',
      ground_name: 'Brooklands, Mill Lane, Broomfield',
      ground_id: '',
      ground_latitude: '',
      ground_longitude: '',
      home_club_name: 'Broomfield CC',
      home_team_name: '2nd XI',
      home_team_id: '50814',
      home_club_id: '1486',
      away_club_name: 'Navestock CC',
      away_team_name: '2nd XI',
      away_team_id: '204936',
      away_club_id: '4513',
      umpire_1_name: '',
      umpire_1_id: '',
      umpire_2_name: '',
      umpire_2_id: '',
      umpire_3_name: '',
      umpire_3_id: '',
      referee_name: '',
      referee_id: '',
      scorer_1_name: '',
      scorer_1_id: '',
      scorer_2_name: '',
      scorer_2_id: '',
    },
  ],
};
